### ISSUE TITLE
链接broken

### ISSUE THREAD

**Issue by sv158** [jschwinger23/jschwinger23.github.io#6]
https://github.com/jschwinger23/jschwinger23.github.io/blob/master/_posts/2018-04-09-%E5%85%B6%E5%AE%9E%E6%88%91%E4%B8%8D%E4%BC%9A-Python.md 里面的 <<听说你会 Python>>打开是白的，没搞明白是什么原因。google了一下倒是其他地方都有转载

**Comment by jschwinger233** [comment]
我能打开... https://manjusaka.itscoder.com/2016/11/18/Someone-tell-me-that-you-think-Python-is-simple/

**Comment by sv158** [comment]
这样啊，那就可能是墙或线路的问题了。

**Comment by jschwinger233** [comment]
因为我在墙外所以不能验证, 不好意思

**Comment by jschwinger233** [comment]
哦确实是 url 又变化, 但不应该是白页, 我改改
